<div class="account-login">
    <div class="page-title">
        <h2><?php echo $this->__('Login or Create an Account') ?></h2>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <div class="row">
            <div class="large-6 columns new-users">
                <div class="content">
                    <h4><?php echo $this->__('New Customers') ?></h4>
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                </div>
                <div class="buttons-set">
                    <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><?php echo $this->__('Create an Account') ?></button>
                </div>
            </div>
            <div class="large-6 columns registered-users">
                <div class="content">
                    <h4><?php echo $this->__('Registered Customers') ?></h4>
                    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list row">
                        <li class="small-6 columns">
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li class="small-6 columns">
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button>
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="forgotten-password"><?php echo $this->__('Forgot Your Password?') ?></a>
                </div>
                <div class="buttons-set oauht-buttons">
                    <?php if (Mage::helper('stuntcoders_customerlogin/facebook')->isEnabled() || Mage::helper('stuntcoders_customerlogin/google')->isEnabled() || Mage::helper('stuntcoders_customerlogin/linkedin')->isEnabled()): ?>
                        <p><?php echo $this->__('Or connect with:'); ?></p>
                    <?php endif; ?>
                    <?php if (Mage::helper('stuntcoders_customerlogin/facebook')->isEnabled()): ?>
                        <a href="<?php echo Mage::helper('stuntcoders_customerlogin/facebook')->getAuthUrl(); ?>" class="button button-facebook"><?php echo $this->__('Facebook'); ?></a>
                    <?php endif; ?>
                    <?php if (Mage::helper('stuntcoders_customerlogin/google')->isEnabled()): ?>
                        <a href="<?php echo Mage::helper('stuntcoders_customerlogin/google')->getAuthUrl(); ?>" class="button button-google"><?php echo $this->__('Google'); ?></a>
                    <?php endif; ?>
                    <?php if (Mage::helper('stuntcoders_customerlogin/linkedin')->isEnabled()): ?>
                        <a href="<?php echo Mage::helper('stuntcoders_customerlogin/linkedin')->getAuthUrl(); ?>" class="button button-linkedin"><?php echo $this->__('LinkedIn'); ?></a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>
